/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBS.Farmaceut;
import DBS.Smlouva;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Adilbek Utemissov
 */
public class Details extends javax.swing.JFrame {

    private int nsmlouva;
    
    private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("Pharmacy");

    private Farmaceut cust;
    /**
     * Creates new form Details
     */
    public Details(int nsmlouva) {
        initComponents();
        this.nsmlouva = nsmlouva;
        view();
    }
    
    private void view() {
        Save.setVisible(false);
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        String query = "SELECT c FROM Smlouva c WHERE c.nsmlouva = :nsmlouva";

        // Issue the query and get a matching Customer
        TypedQuery<Smlouva> tq = em.createQuery(query, Smlouva.class);
        tq.setParameter("nsmlouva", nsmlouva);

        Smlouva cust = null;
        try {
            // Get matching customer object and output
            cust = tq.getSingleResult();
            Integer intInstance = cust.getNsmlouva();
            NSmlouvyText.setText(intInstance.toString());
            NSmlouvyText.setEditable(false);
            intInstance = cust.getIcolekarna();
            IcoLekText.setText(intInstance.toString());
            IcoLekText.setEditable(false);
            intInstance = cust.getIcofarmspol();
            IcoSpolText.setText(intInstance.toString());
            IcoSpolText.setEditable(false);
            PrijemceText.setText(cust.getPrijemce());
            PrijemceText.setEditable(false);
            DodavatelText.setText(cust.getDodavatel());
            DodavatelText.setEditable(false);
            ZacatekText.setText(cust.getZacatek());
            ZacatekText.setEditable(false);
            KonecText.setText(cust.getKonec());
            KonecText.setEditable(false);

        } catch(Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smlouva = new javax.swing.JPanel();
        Zpet = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        NSmlouvyTitle = new javax.swing.JLabel();
        IcoSpolTitle = new javax.swing.JLabel();
        IcoLekTitle = new javax.swing.JLabel();
        DodavatelTitle = new javax.swing.JLabel();
        PrijemceTitle = new javax.swing.JLabel();
        ZacatekTitle = new javax.swing.JLabel();
        KonceTitle = new javax.swing.JLabel();
        NSmlouvyText = new javax.swing.JTextField();
        IcoSpolText = new javax.swing.JTextField();
        IcoLekText = new javax.swing.JTextField();
        DodavatelText = new javax.swing.JTextField();
        PrijemceText = new javax.swing.JTextField();
        ZacatekText = new javax.swing.JTextField();
        KonecText = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        smlouva.setBackground(new java.awt.Color(44, 62, 80));

        Zpet.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Zpet.setText("Zpět");
        Zpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZpetMouseClicked(evt);
            }
        });

        Edit.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Edit.setText("Zmenit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        NSmlouvyTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NSmlouvyTitle.setForeground(new java.awt.Color(255, 255, 255));
        NSmlouvyTitle.setText("Číslo smlouvy:");

        IcoSpolTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        IcoSpolTitle.setForeground(new java.awt.Color(255, 255, 255));
        IcoSpolTitle.setText("ICO společnosti:");

        IcoLekTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        IcoLekTitle.setForeground(new java.awt.Color(255, 255, 255));
        IcoLekTitle.setText("ICO lekárny:");

        DodavatelTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        DodavatelTitle.setForeground(new java.awt.Color(255, 255, 255));
        DodavatelTitle.setText("Dodavatel:");

        PrijemceTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PrijemceTitle.setForeground(new java.awt.Color(255, 255, 255));
        PrijemceTitle.setText("Příjemce:");

        ZacatekTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ZacatekTitle.setForeground(new java.awt.Color(255, 255, 255));
        ZacatekTitle.setText("Začátek:");

        KonceTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        KonceTitle.setForeground(new java.awt.Color(255, 255, 255));
        KonceTitle.setText("Konec:");

        NSmlouvyText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        IcoSpolText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        IcoLekText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        DodavatelText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        PrijemceText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        ZacatekText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ZacatekText.setToolTipText("");

        KonecText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Save.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Save.setText("Uložit");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Remove.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Remove.setText("Smazat");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smlouvaLayout = new javax.swing.GroupLayout(smlouva);
        smlouva.setLayout(smlouvaLayout);
        smlouvaLayout.setHorizontalGroup(
            smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smlouvaLayout.createSequentialGroup()
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smlouvaLayout.createSequentialGroup()
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NSmlouvyTitle)
                                    .addComponent(IcoSpolTitle)
                                    .addComponent(IcoLekTitle)
                                    .addComponent(DodavatelTitle)
                                    .addComponent(PrijemceTitle)
                                    .addComponent(ZacatekTitle)
                                    .addComponent(KonceTitle)))
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KonecText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IcoLekText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IcoSpolText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NSmlouvyText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ZacatekText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrijemceText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DodavatelText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(smlouvaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        smlouvaLayout.setVerticalGroup(
            smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smlouvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NSmlouvyTitle)
                    .addComponent(NSmlouvyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IcoSpolTitle)
                    .addComponent(IcoSpolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IcoLekTitle)
                    .addGroup(smlouvaLayout.createSequentialGroup()
                        .addComponent(IcoLekText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DodavatelTitle)
                            .addComponent(DodavatelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrijemceTitle)
                            .addComponent(PrijemceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZacatekTitle)
                            .addComponent(ZacatekText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KonceTitle)
                            .addComponent(KonecText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlouva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlouva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        EntityTransaction et = null;
        Smlouva cu = null;

        try {
            et = em.getTransaction();
            et.begin();
            cu = em.find(Smlouva.class, nsmlouva);
            em.remove(cu);
            et.commit();
        } catch (Exception ex) {
            // If there is an exception rollback changes
            if (et != null) {
                et.rollback();
            }
            ex.printStackTrace();
        } finally {
            // Close EntityManager
            em.close();
            JOptionPane.showMessageDialog(null, "Smlouva smazana uspesne");
            this.cust = cust;
            HomePage hm = new HomePage(cust);
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Save.setVisible(true);
        Remove.setVisible(false);
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        EntityTransaction et = null;

        Smlouva cu = null;
        try {
            et = em.getTransaction();
            et.begin();
            // Get matching customer object and output
            cu = em.find(Smlouva.class, nsmlouva);

            cu.setNsmlouva(Integer.parseInt(NSmlouvyText.getText()));
            cu.setIcolekarna(Integer.parseInt(IcoLekText.getText()));
            cu.setIcofarmspol(Integer.parseInt(IcoSpolText.getText()));
            cu.setPrijemce(PrijemceText.getText());
            cu.setDodavatel(DodavatelText.getText());
            cu.setZacatek(ZacatekText.getText());
            cu.setKonec(KonecText.getText());
            em.persist(cu);
            et.commit();
        } catch(Exception e) {
            if (et != null) {
                et.rollback();
            }
            e.printStackTrace();
        } finally {
            // Close EntityManager
            em.close();
            JOptionPane.showMessageDialog(null, "Zmena provedla uspesne");
            this.cust = cust;
            HomePage hm = new HomePage(cust);
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        Save.setVisible(true);
        IcoLekText.setEditable(true);
        IcoSpolText.setEditable(true);
        PrijemceText.setEditable(true);
        DodavatelText.setEditable(true);
        ZacatekText.setEditable(true);
        KonecText.setEditable(true);
    }//GEN-LAST:event_EditActionPerformed

    private void ZpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZpetMouseClicked
        ViewContracts vc = new ViewContracts(cust);
        vc.setVisible(true);
        vc.pack();
        vc.setLocationRelativeTo(null);
        vc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ZpetMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DodavatelText;
    private javax.swing.JLabel DodavatelTitle;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField IcoLekText;
    private javax.swing.JLabel IcoLekTitle;
    private javax.swing.JTextField IcoSpolText;
    private javax.swing.JLabel IcoSpolTitle;
    private javax.swing.JLabel KonceTitle;
    private javax.swing.JTextField KonecText;
    private javax.swing.JTextField NSmlouvyText;
    private javax.swing.JLabel NSmlouvyTitle;
    private javax.swing.JTextField PrijemceText;
    private javax.swing.JLabel PrijemceTitle;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Save;
    private javax.swing.JTextField ZacatekText;
    private javax.swing.JLabel ZacatekTitle;
    private javax.swing.JButton Zpet;
    private javax.swing.JPanel smlouva;
    // End of variables declaration//GEN-END:variables
}
