/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBS.Farmaceut;
import DBS.Smlouva;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Adilbek Utemissov
 */
public class DetailsMyContract extends javax.swing.JFrame {

    private int nsmlouva;
    
    private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("Pharmacy");

    private Farmaceut cust;
    
    /**
     * Creates new form Details
     */
    public DetailsMyContract(int nsmlouva) {
        initComponents();
        this.nsmlouva = nsmlouva;
        view();
//        this.nsmlouva = nsmlouva;
    }
    
    private void view() {
        Save.setVisible(false);
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        EntityTransaction et = null;
        
        Farmaceut farm = null;
        Smlouva sm = null;
        
        try {
            // Get transaction and start
            et = em.getTransaction();
            et.begin();
                        
            List<Smlouva> smlouvy = new ArrayList<>();

            smlouvy = cust.getSmlouvy();
            
            System.out.println(smlouvy);
            
        } catch(Exception e) {}
        finally {
            em.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smlouva = new javax.swing.JPanel();
        Zpet = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        NSmlouvyTitle = new javax.swing.JLabel();
        NSmlouvyText = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        smlouva.setBackground(new java.awt.Color(44, 62, 80));

        Zpet.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Zpet.setText("Zpět");
        Zpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZpetMouseClicked(evt);
            }
        });

        Edit.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Edit.setText("Zmenit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        NSmlouvyTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NSmlouvyTitle.setForeground(new java.awt.Color(255, 255, 255));
        NSmlouvyTitle.setText("Číslo smlouvy:");

        NSmlouvyText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Save.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Save.setText("Uložit");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Remove.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Remove.setText("Smazat");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smlouvaLayout = new javax.swing.GroupLayout(smlouva);
        smlouva.setLayout(smlouvaLayout);
        smlouvaLayout.setHorizontalGroup(
            smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smlouvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smlouvaLayout.createSequentialGroup()
                        .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smlouvaLayout.createSequentialGroup()
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(NSmlouvyTitle)))
                        .addGap(18, 18, 18)
                        .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(smlouvaLayout.createSequentialGroup()
                                .addComponent(NSmlouvyText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        smlouvaLayout.setVerticalGroup(
            smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smlouvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NSmlouvyTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NSmlouvyText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183)
                .addGroup(smlouvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlouva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlouva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ZpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZpetMouseClicked
//        ViewContracts vc = new ViewContracts();
//        vc.setVisible(true);
//        vc.pack();
//        vc.setLocationRelativeTo(null);
//        vc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();
    }//GEN-LAST:event_ZpetMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        Save.setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
////        Save.setVisible(true);
////        Remove.setVisible(false);
////        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
////        EntityTransaction et = null;
////
////        Smlouva cu = null;
////        try {
////            List<Smlouva> smlouvy = new ArrayList<>();
////
////            smlouvy = cust.getSmlouvy();            
////            
////            em.persist(cust);
////            et.commit();
////        } catch(Exception e) {
////            if (et != null) {
////                et.rollback();
////            }
////            e.printStackTrace();
////        } finally {
////            // Close EntityManager
////            em.close();
////            JOptionPane.showMessageDialog(null, "Zmena provedla uspesne");
////            this.cust = cust;
////            HomePage hm = new HomePage(cust);
////            hm.setVisible(true);
////            hm.pack();
////            hm.setLocationRelativeTo(null);
////            hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
////            this.dispose();
////        }
    }//GEN-LAST:event_SaveActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
//        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
//        EntityTransaction et = null;
//        Smlouva cu = null;
//
//        try {
//            et = em.getTransaction();
//            et.begin();
////            cu = em.find(Smlouva.class, nsmlouva);
//            em.remove(cust);
//            et.commit();
//        } catch (Exception ex) {
//            // If there is an exception rollback changes
//            if (et != null) {
//                et.rollback();
//            }
//            ex.printStackTrace();
//        } finally {
//            // Close EntityManager
//            em.close();
//            JOptionPane.showMessageDialog(null, "Smlouva smazana uspesne");
//            this.cust = cust;
//            HomePage hm = new HomePage(cust);
//            hm.setVisible(true);
//            hm.pack();
//            hm.setLocationRelativeTo(null);
//            hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            this.dispose();
//        }
    }//GEN-LAST:event_RemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField NSmlouvyText;
    private javax.swing.JLabel NSmlouvyTitle;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Save;
    private javax.swing.JButton Zpet;
    private javax.swing.JPanel smlouva;
    // End of variables declaration//GEN-END:variables
}
