/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBS.Farmaceut;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Adilbek Utemissov
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("Pharmacy");
     private Farmaceut cust;
    public String heslo;
    
    public int ico;


    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);//center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prihlaseni = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        EmailTitle = new javax.swing.JLabel();
        PasswordTitle = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Registrace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prihlaseni.setBackground(new java.awt.Color(44, 62, 80));

        Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Přihlášení");

        EmailTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        EmailTitle.setForeground(new java.awt.Color(255, 255, 255));
        EmailTitle.setText("Email");

        PasswordTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTitle.setText("Heslo");

        EmailText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        PasswordText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Login.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Login.setText("Login");
        Login.setMaximumSize(new java.awt.Dimension(124, 38));
        Login.setMinimumSize(new java.awt.Dimension(124, 38));
        Login.setPreferredSize(new java.awt.Dimension(124, 38));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Registrace.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Registrace.setText("Registrace");
        Registrace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistraceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prihlaseniLayout = new javax.swing.GroupLayout(prihlaseni);
        prihlaseni.setLayout(prihlaseniLayout);
        prihlaseniLayout.setHorizontalGroup(
            prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prihlaseniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registrace, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299)
                .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(prihlaseniLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordTitle)
                    .addComponent(EmailTitle))
                .addGap(35, 35, 35)
                .addGroup(prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prihlaseniLayout.setVerticalGroup(
            prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prihlaseniLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Title)
                .addGap(70, 70, 70)
                .addGroup(prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmailTitle)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(prihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Title.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prihlaseni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prihlaseni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistraceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistraceMouseClicked
        RegistraceForm rgf = new RegistraceForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_RegistraceMouseClicked

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        final String secretKey = "ssshhhhhhhhhhh!!!!";
        
        String email = EmailText.getText();
        String password = String.valueOf(PasswordText.getPassword());
        
        heslo = Hashing.encrypt(password, secretKey);

        // the lowercase c refers to the object
        // :custID is a parameterized query thats value is set below
        String query = "SELECT c FROM Farmaceut c WHERE c.email = :email AND c.heslo = :heslo";

        // Issue the query and get a matching Customer
        TypedQuery<Farmaceut> tq = em.createQuery(query, Farmaceut.class);
        tq.setParameter("email", email);
        tq.setParameter("heslo", heslo);

        Farmaceut cust = null;
        try {
            // Get matching customer object and output
            cust = tq.getSingleResult();
            this.cust = cust;
            HomePage hm = new HomePage(cust);
            hm.setVisible(true);
            hm.pack();
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Spatne napsano email nebo heslo");
        }
        finally {
            em.close();
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EmailTitle;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JButton Registrace;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel prihlaseni;
    // End of variables declaration//GEN-END:variables
}
