/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBS.Farmaceut;
import java.beans.Statement;
import java.sql.ResultSet;
import project.Hashing;

import java.sql.*;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Adilbek Utemissov
 */
public class RegistraceForm extends javax.swing.JFrame {
    
    private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("Pharmacy");
    
    public String encryptedString;
    
    /**
     * Creates new form RegistraceForm
     */
    public RegistraceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrace = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NameTitle = new javax.swing.JLabel();
        LastnameTitle = new javax.swing.JLabel();
        EmailTitle = new javax.swing.JLabel();
        PasswordTitle = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        LastnameText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        Cancel = new javax.swing.JButton();
        Registrace = new javax.swing.JButton();
        IcolekarnaTitle = new javax.swing.JLabel();
        icolekarnaText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrace.setBackground(new java.awt.Color(44, 62, 80));
        registrace.setPreferredSize(new java.awt.Dimension(526, 350));

        Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Registrace");

        NameTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NameTitle.setForeground(new java.awt.Color(255, 255, 255));
        NameTitle.setText("Jmeno");

        LastnameTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LastnameTitle.setForeground(new java.awt.Color(255, 255, 255));
        LastnameTitle.setText("Příjmení");

        EmailTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        EmailTitle.setForeground(new java.awt.Color(255, 255, 255));
        EmailTitle.setText("Email");

        PasswordTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTitle.setText("Heslo");

        NameText.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        LastnameText.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        EmailText.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        PasswordText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PasswordText.setMinimumSize(new java.awt.Dimension(14, 25));

        Cancel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Cancel.setText("Zpět");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        Registrace.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Registrace.setText("Registrace");
        Registrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraceActionPerformed(evt);
            }
        });

        IcolekarnaTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        IcolekarnaTitle.setForeground(new java.awt.Color(255, 255, 255));
        IcolekarnaTitle.setText("ICO lekarny");

        icolekarnaText.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        icolekarnaText.setMinimumSize(new java.awt.Dimension(14, 25));

        javax.swing.GroupLayout registraceLayout = new javax.swing.GroupLayout(registrace);
        registrace.setLayout(registraceLayout);
        registraceLayout.setHorizontalGroup(
            registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraceLayout.createSequentialGroup()
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registraceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Registrace, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registraceLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTitle)
                            .addComponent(NameTitle)
                            .addComponent(PasswordTitle)
                            .addComponent(LastnameTitle)
                            .addComponent(IcolekarnaTitle))
                        .addGap(35, 35, 35)
                        .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icolekarnaText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LastnameText)
                                .addComponent(EmailText)
                                .addComponent(NameText)
                                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(registraceLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registraceLayout.setVerticalGroup(
            registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraceLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Title)
                .addGap(32, 32, 32)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTitle))
                .addGap(33, 33, 33)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastnameTitle)
                    .addComponent(LastnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registraceLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(EmailTitle))
                    .addGroup(registraceLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registraceLayout.createSequentialGroup()
                        .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordTitle))
                        .addGap(33, 33, 33)
                        .addComponent(IcolekarnaTitle))
                    .addComponent(icolekarnaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrace, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrace, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void RegistraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraceActionPerformed
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        EntityTransaction et = null;
        final String secretKey = "ssshhhhhhhhhhh!!!!";
        
        String fname = NameText.getText();
        String lname = LastnameText.getText();
        String email = EmailText.getText();
        String password = String.valueOf(PasswordText.getPassword());
        int ico = Integer.parseInt(icolekarnaText.getText());
        
        try {
            // Get transaction and start
            et = em.getTransaction();
            et.begin();
            
            encryptedString = Hashing.encrypt(password, secretKey);
 
            Farmaceut cust = new Farmaceut();
            // Create and set values for new customer
            cust.setIcolekarna(ico);
            cust.setJmeno(fname);
            cust.setPrijmeni(lname);
            cust.setEmail(email);
            cust.setHeslo(encryptedString);

            // Save the customer object
            em.persist(cust);
            et.commit();
        } catch (Exception ex) {
            // If there is an exception rollback changes
            JOptionPane.showMessageDialog(null, "asd pridan uspesne");
            if (et != null) {
                et.rollback();
            }
        } finally {
            // Close EntityManager
            em.close();
            JOptionPane.showMessageDialog(null, "Farmaceut pridan uspesne");
        }
    }//GEN-LAST:event_RegistraceActionPerformed

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_CancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EmailTitle;
    private javax.swing.JLabel IcolekarnaTitle;
    private javax.swing.JTextField LastnameText;
    private javax.swing.JLabel LastnameTitle;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel NameTitle;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JButton Registrace;
    private javax.swing.JLabel Title;
    private javax.swing.JPasswordField icolekarnaText;
    private javax.swing.JPanel registrace;
    // End of variables declaration//GEN-END:variables
}
