/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import DBS.Farmaceut;
import DBS.Smlouva;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Adilbek Utemissov
 */
public class ViewContracts extends javax.swing.JFrame {
    
    private static ArrayList<Integer> index;
    
    private static final EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("Pharmacy");

    private Farmaceut cust;

    /**
     * Creates new form ViewContracts
     */
    public ViewContracts(Farmaceut cust) {
        initComponents();
        this.cust = cust;
        list.setMultipleMode(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Hledani = new javax.swing.JPanel();
        Zpet = new javax.swing.JButton();
        PasswordTitle = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Hledat = new javax.swing.JButton();
        icolekarnaText = new javax.swing.JTextField();
        list = new java.awt.List();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Hledani.setBackground(new java.awt.Color(44, 62, 80));

        Zpet.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Zpet.setText("Zpět");
        Zpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZpetMouseClicked(evt);
            }
        });

        PasswordTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        PasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTitle.setText("ICO lekarny");

        Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Hledani");

        Hledat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Hledat.setText("Hledat");
        Hledat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HledatActionPerformed(evt);
            }
        });

        icolekarnaText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        list.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HledaniLayout = new javax.swing.GroupLayout(Hledani);
        Hledani.setLayout(HledaniLayout);
        HledaniLayout.setHorizontalGroup(
            HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HledaniLayout.createSequentialGroup()
                .addGroup(HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HledaniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hledat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HledaniLayout.createSequentialGroup()
                        .addGroup(HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HledaniLayout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(Title))
                            .addGroup(HledaniLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(PasswordTitle)
                                .addGap(27, 27, 27)
                                .addComponent(icolekarnaText, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HledaniLayout.setVerticalGroup(
            HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HledaniLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordTitle)
                    .addComponent(icolekarnaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HledaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zpet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hledat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hledani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hledani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZpetMouseClicked
        HomePage hm = new HomePage(cust);
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ZpetMouseClicked

    private void HledatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HledatActionPerformed
        EntityManager em = ENTITY_MANAGER_FACTORY.createEntityManager();
        EntityTransaction et = null;

        if(icolekarnaText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pole je prazdna");
            if (et != null) {
                et.rollback();
            }     
        } else {
            int icolekarna = Integer.parseInt(icolekarnaText.getText());
            index = new ArrayList<>();
            list.clear();
            //the lowercase c refers to the object
            //:custID is a parameterized query thats value is set below
            String strQuery = "SELECT c FROM Smlouva c WHERE c.icolekarna = :icolekarna";
            
            //Issue the query and get a matching Customer
            TypedQuery<Smlouva> tq = em.createQuery(strQuery, Smlouva.class);

            tq.setParameter("icolekarna", icolekarna);
            
            List<Smlouva> custs;

            try {
                //Get matching customer object and output
                custs = tq.getResultList();
                for(int i=0; i<custs.size(); i++) {
                    if(cust.getIcolekarna() == custs.get(i).getIcolekarna()) {
                        list.add(custs.get(i).getNsmlouva() + "        " + custs.get(i).getIcolekarna()+ "       " + custs.get(i).getIcofarmspol() + "        " + custs.get(i).getZacatek() + "        " + custs.get(i).getKonec() + "      " + custs.get(i).getPrijemce() + "      " + custs.get(i).getDodavatel());
                        index.add(custs.get(i).getNsmlouva());
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Nemate pristup");
                        et.rollback();
                    }
                }
                if(custs.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Zadana smlouva neni nalezena");
                    if (et != null) {
                        et.rollback();
                    }     
                }
            } catch(Exception e) {
            }
            finally {
                em.close();
            }
        }
    }//GEN-LAST:event_HledatActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        Details dt = new Details(index.get(list.getSelectedIndex()));
        dt.setVisible(true);
        dt.pack();
        dt.setLocationRelativeTo(null);
        dt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_listActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hledani;
    private javax.swing.JButton Hledat;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Zpet;
    private javax.swing.JTextField icolekarnaText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.List list;
    // End of variables declaration//GEN-END:variables
}
